services:
  - type: web
    name: linkedin-comment-extractor
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    healthCheckPath: /
    autoDeploy: true 